////
 Copyright (c) 2024 Software AG, Darmstadt, Germany and/or Software AG USA Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors.
 Use, reproduction, transfer, publication or disclosure is prohibited except as specifically provided for in your License Agreement with Software AG.
////
= Using Terracotta BigMemory with Docker
{docdate}
:top: ../..
:stylesdir: {top}/stylesheets

*Prerequisites*:

You must have a functional Docker environment and a foundational understanding of Docker operations. This includes tasks such as installing and configuring Docker, managing Docker images by starting and stopping them, and configuring fundamental options like volumes and port forwarding.

== Introduction to Docker and Terracotta Bigmemory

Docker's containerization technology enables seamless deployment and management of Terracotta instances across diverse environments, from development to production, ensuring consistent performance and resource utilization. This portability and reproducibility eliminate deployment issues caused by environmental differences, ensuring that Terracotta clusters behave identically regardless of the underlying infrastructure.

One of the key advantages of this integration is the ability to rapidly provision and scale Terracotta clusters to meet changing demands and workload fluctuations. With Docker's flexibility, organizations can horizontally scale their Terracotta clusters by spinning up additional containers, allowing them to respond swiftly to increased traffic or data processing requirements.

Furthermore, Docker's orchestration capabilities, in combination with tools like Kubernetes or Docker Swarm, simplify the management and monitoring of Terracotta clusters at scale. Automated deployment, scaling, and failover mechanisms ensure high availability and resilience, minimizing downtime and maximizing operational efficiency.

By packaging Terracotta BigMemory instances as Docker containers, organizations can achieve scalability and efficiency in handling caching and operational storage use cases. For example, containerized Terracotta clusters can be leveraged for high-performance caching of frequently accessed data, reducing database load and improving application responsiveness.

In essence, integrating Terracotta BigMemory with Docker allows organizations to fully leverage the power of distributed in-memory data caching while embracing the scalability and portability offered by containerization. This integration enables seamless deployment, efficient resource utilization, and rapid scaling while minimizing infrastructure complexity.

== Terracotta BigMemory Docker Images

You'll interact with various components when deploying and managing Terracotta clusters using Docker. Let's dive into the key components and how you can leverage them.

* *Terracotta Server*

The Terracotta Server is the backbone of your Terracotta cluster. It's responsible for coordinating data management and clustering operations.

To set up a cluster, you'll need to launch multiple instances of the Terracotta Server Docker image, with each instance representing a cluster node. Terracotta cluster nodes are grouped by stripes.

* *Terracotta Management Server*

For a comprehensive web-based monitoring and management experience, Terracotta provides the Management Server. This application offers detailed insights into cluster health, performance metrics, and resource utilization, allowing you to proactively manage and optimize your Terracotta cluster.

All these components are available as Docker images on the webMethods.io Docker registry available at link:https://containers.webmethods.io[https://containers.webmethods.io, window="_blank"]

== Terracotta Server

=== Pulling the Terracotta Server Docker Image

To pull the Terracotta Server image, use the following command:

[source,shell]
----
docker pull docker pull sagcr.azurecr.io/bigmemorymax-server:<version>
----

`Replace <version> with the desired Terracotta Server version, such as 4.4`

=== Prerequisite for starting a Terracotta Server Container

Before launching your cluster, it's essential to prepare a configuration file (`tc-config.xml`) to configure your Terracotta cluster.

Additionally, you'll need to obtain a license (`license.key`).

For detailed information, please consult the official link:https://documentation.softwareag.com/terracotta/terracotta_440/webhelp/bigmemory-max-webhelp/index.html[Terracotta BigMemory documentation].

=== Starting a Terracotta Server Instance

To start a Terracotta Server instance as a Docker container, you'll use the `docker run` command with the appropriate parameters. Here's an example:

[source,shell]
----
docker run -d \
      -v /path/to/config-directory:/opt/softwareag/config:ro \
      -p 9410:9410 \
      -h terracotta-server-1 \
      --network terracotta-net \
      --name terracotta-server-1 \
      sagcr.azurecr.io/bigmemorymax-server:4.4
----

Let's break down the parameters:

* `-d`: Runs the container in detached mode, allowing it to run in the background.
* `-v /path/to/config-directory` path to the folder containing the `license.key` and the `tc-config.xml` files.
* `-p 9410:9410`: Maps the container's port 9410 to the host's port 9410. The Terracotta Server uses this port for inter-server communication, so you need to expose it. If a different port has been configured in the tc-config.xml, make sure to map the right one.
* `-h terracotta-server-1`: Sets the hostname for the container to `terracotta-server-1`. This hostname is used for identification within the Terracotta cluster.
* `--network terracotta-net`: Specifies the Docker network that the container should join. In this case, it's `terracotta-net`. This network allows the Terracotta Server instances to communicate with each other and form a cluster.
* `--name terracotta-server-1`: Assigns a name to the container for easy identification and management.
* `sagcr.azurecr.io/bigmemorymax-server:4.4`: Specifies the Docker image to use.

To set up a Terracotta cluster, you'll need to launch multiple instances of the Terracotta Server Docker image, with each instance running in a separate container. These instances will communicate with each other over the specified network (`terracotta-net` in the example) and form a cluster.

==== Example

Here is an example of a link:examples/tc-config.xml[tc-config.xml], which would be located in the `/Users/docker-test/` folder, along with the `license.key` file. The commands to start the cluster would be:



[source,shell]
----
docker run -d \
      -v /Users/docker-test:/opt/softwareag/config:ro \
      -p 9510:9510 \
      -h terracotta-server-1 \
      --network terracotta-net \
      --name terracotta-server-1 \
      sagcr.azurecr.io/bigmemorymax-server:4.4

docker run -d \
      -v /Users/docker-test:/opt/softwareag/config:ro \
      -p 9511:9511 \
      -h terracotta-server-2 \
      --network terracotta-net \
      --name terracotta-server-2 \
      sagcr.azurecr.io/bigmemorymax-server:4.4
----

=== Additional Parameters

**Persisting Terracotta Server Data with Docker Volumes**

By default, data and log files are persisted next to the XML configuration file. However, please note that the persisted data will be owned by the user ID from the container, potentially restricting cleanup operations from the host machine.

Ensure that the chmod (777) permission is set for your mount folder so that the container user can write to the specified location.

To ensure data persistence, you can leverage Docker volumes by mounting a host directory to the container's `/opt/softwareag/run` directory. Here's an example `docker run` command:

[source,shell]
----
docker run -d \
      -v /path/to/config-directory:/opt/softwareag/config:ro \
      -v /path/to/data-directory:/opt/softwareag/run \
      -p 9510:9510 \
      -h terracotta-server-1 \
      --network terracotta-net \
      --name bigmemorymax-server-1 \
      sagcr.azurecr.io/bigmemorymax-server:4.4
----

**Configuring Java Heap Size**

Additionally, you can configure the Java heap size for the Terracotta Server JVM using the `JAVA_OPTS` environment variable. For instance:

[source,bash]
----
docker run -d \
      -e JAVA_OPTS="-Xmx8G" \
      ...
----

This sets the maximum Java heap size to 8GB (`-Xmx=8G`).

**Enabling JSON Logging**

In specific scenarios, you may want to enable JSON logging for the Terracotta Server. To activate JSON logging, use the `JSON_LOGGING` environment variable:

[source,bash]
----
docker run -d \
      -e JSON_LOGGING=true \
      ...
----

=== Configuring Terracotta Server Security

In addition to memory and logging configurations, you can also set up security for your Terracotta Server instances running in Docker containers.

The Terracotta Server reads security files from the location specified in the `tc-config.xml` file. Since you have mounted the `/opt/softwareag/config` directory to a local volume, you can specify this folder in `tc-config.xml` for the security file location and place the security files in the corresponding local directory.

Please ensure that the Docker process has the necessary permissions to access and read the security configuration files in the mounted directory.

== Terracotta Management Server

The Terracotta Management Server (TMS) offers real-time information about the Terracotta cluster, accessible through The Terracotta Management Console (TMC) via a web interface.

To retrieve the TMS Docker image, use:

[source,shell]
----
docker pull sagcr.azurecr.io/bigmemorymax-management-server:<version>
----

To access the TMC, you need to expose the port from the container to the host. Here's an example command:

[source,shell]
----
docker run -d \
      -v /path/to/license-directory:/opt/softwareag/config:ro \
      -v /path/to/config-directory:/opt/softwareag/.tc/mgmt \
      -p 9889:9889 \
      -h terracotta-management-server \
      --network terracotta-net \
      --name terracotta-management-server \
      sagcr.azurecr.io/bigmemorymax-management-server:4.4
----

Let's break down the parameters:

* `-v /path/to/license-directory` path to the folder containing the `license.key` file.
* `/path/to/config-directory:/opt/softwareag/.tc/mgmt` path to the folder where the `settings.ini` configuration file will be stored. If it is not present, a new one will be created during the first run.
* `-p 9889:9889`: Maps the container's port 9889 to the host's port 9889. This the public port to access the Management Server in the browser.
* `-h terracotta-management-server`: Sets the hostname for the container to `terracotta-management-server`. This hostname is used for identification within the Terracotta cluster.
* `--network terracotta-net`: Specifies the Docker network that the container should join. In this case, it's `terracotta-net`. This network allows the Terracotta Server instances to communicate with each other and form a cluster.
* `--name terracotta-management-1`: Assigns a name to the container for easy identification and management.
* `sagcr.azurecr.io/bigmemorymax-management:4.4`: Specifies the Docker image to use.

You can then access the TMC via a web browser (``http://<docker-host-hostname>:9889``, where ``docker-host-hostname`` is the hostname of your docker host). If you ran the commands locally, you can access to the Management server on `http://localhost:9889`

The first time, you will have to choose to configure authentication or not, then restart the docker image.

[source,shell]
----
docker restart terracotta-management-server
----

The local `settings.ini` will then be updated.

You will specify the path to the security configuration files in this file if the cluster is secured.

=== Configuring Terracotta Management Server Security

To configure security in TMC, add the following files into your config folder:

   * `license.key`: The license
   * `keychain`: Stores credentials for keystore and truststore
   * `tmc-https.ini`: Used to store Jetty SSL connector credentials
   * `keystore.jks`: Used for Jetty SSL connector
   * `truststore.jks`: Used for Jetty SSL connector


[source,shell]
----
docker run -d \
      -v /path/to/config-directory/for/tmc:/opt/softwareag/config:ro \
      -v /path/to/config-directory/for/tc/home:/opt/softwareag/.tc/mgmt \
      -e JAVA_OPTS="-Djavax.net.ssl.keyStore=/opt/softwareag/.tc/mgmt/keystore.jks -Djavax.net.ssl.trustStore=/opt/softwareag/.tc/mgmt/truststore.jks" \
      -p 9889:9889 \
      -p 9443:9443 \
      -h bigmemorymax-tmc \
      --network terracotta-net \
      --name terracotta-management-server \
      sagcr.azurecr.io/bigmemorymax-management-server:4.4
----

Note:

    Security needs persistence because a setup is required and a container restart
    Configuration files are all copied into /opt/softwareag/.tc/mgmt. So you can use /opt/softwareag/.tc/mgmt when generating the keychain file as the base path for the keystore and truststore.

