# Site settings
title: Terracotta
email: tc-oss@wwpdl.vnet.ibm.com
description: >-
  Terracotta provides powerful distributed in-memory data management
  capabilities for Terracotta products and is the backbone for Terracotta clusters.
baseurl: ""
url: "https://www.terracotta.org"
github_username: terracotta-oss

# Build settings
markdown: kramdown
plugins:
  - jekyll-asciidoc
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-toc

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - postcss.config.js
  - tailwind.config.js
  - README.md
  - vendor
  - .github
  - apidocs

asciidoctor:
  attributes:
    - source-highlighter=prism
    - icons=font
    - sectanchors
    - idprefix
    - idseparator=-

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: "about"
      type: pages
    values:
      layout: about
  - scope:
      path: "community"
      type: pages
    values:
      layout: docs
  - scope:
      path: "documentation"
      type: pages
    values:
      layout: docs