jobs:
  - job:
    timeoutInMinutes: 120
    pool:
      vmImage: 'ubuntu-latest'
    variables: 
    - group: 'netlify-terracotta'
    - group: 'github'

    steps:
      - checkout: self
        persistCredentials: 'true'
        clean: 'true'
      - script: |
          touch Gemfile.lock ; chmod 777 Gemfile.lock
      - bash: |
          set -e
          uname -a
          cat /etc/*elease*
          npm -v
          node -v
          env
          #npm install netlify-cli
          du -sh $BUILD_BINARIESDIRECTORY
          find $BUILD_BINARIESDIRECTORY | wc -l
          echo "Site ID $NETLIFY_SITE_ID"
          #$(npm bin)/netlify deploy -d $BUILD_BINARIESDIRECTORY --json | tee netlify.json
          #NETLIFY_URL=$(jq -r '.deploy_url' netlify.json)
          echo "Informing GitHub about deploy url: ${NETLIFY_URL} via https://api.github.com/repos/Terracotta-OSS/terracotta.org-site/pulls/${SYSTEM_PULLREQUEST_PULLREQUESTNUMBER}/comments"
          #curl -H "Authorization: token ${GTOKEN}" -X POST -d "{\"body\": \"[A Live Preview](${NETLIFY_URL}) of this Pull Request at commit ${SYSTEM_PULLREQUEST_SOURCECOMMITID} is now available\", \"commit_id\": \"${SYSTEM_PULLREQUEST_SOURCECOMMITID}\"}" "https://api.github.com/repos/Terracotta-OSS/terracotta.org-site/pulls/${SYSTEM_PULLREQUEST_PULLREQUESTNUMBER}/comments"
          set -x
          curl -u $GH_USER:$GTOKEN -X POST -d "{\"body\": \"[A Live Preview](${NETLIFY_URL}) of this Pull Request at commit ${SYSTEM_PULLREQUEST_SOURCECOMMITID} is now available\", \"commit_id\": \"${SYSTEM_PULLREQUEST_SOURCECOMMITID}\"}" "https://api.github.com/repos/Terracotta-OSS/terracotta.org-site/issues/${SYSTEM_PULLREQUEST_PULLREQUESTNUMBER}/comments"
        displayName: 'Netlify Publish'
        env:
            NETLIFY_SITE_ID: $(netlify_site_id)
            NETLIFY_AUTH_TOKEN: $(netlify_auth_token)
            GTOKEN: $(gh_temp_token)
        condition: eq(variables['Build.Reason'], 'PullRequest')
