jobs:
  - job:
    timeoutInMinutes: 120
    pool:
      vmImage: 'ubuntu-latest'
    variables: 
    - group: 'netlify-terracotta'
    - group: 'github'

    steps:
      - checkout: self
        persistCredentials: 'true'
        clean: 'true'
      # GitHub Comment v0
      # Write a comment to your GitHub entity i.e. issue or a pull request (PR).
      - task: GitHubComment@0
        inputs:
          gitHubConnection: Terracotta-OSS
          repositoryName: '$(Build.Repository.Name)' # string. Required. Repository. Default: $(Build.Repository.Name).
          #id: # string. ID of the github pr/issue.
          comment: "Test of this Pull Request at commit $(System.PullRequest.SourceCommitId) is now available"
        condition: eq(variables['Build.Reason'], 'PullRequest')
